@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/devicons/react.puml
!includeurl ICONURL/devicons/javascript_badge.puml

AddRelTag("async", $lineStyle = DashedLine())

SHOW_PERSON_PORTRAIT()

Person(visitor, "Visitante", "Usuário que reserva ingressos e livros")
Person(librarian, "Bibliotecário", "Gerencia as reservas e eventos")
Person(admin, "Administrador do Sistema", "Acompanha as métricas do sistema")

System_Boundary(mam_system, "Sistema de Venda de Ingressos e Reserva da Biblioteca - MAM") {
    Container(backend, "Backend", "JavaScript", "Sistema que gerencia reservas de ingressos e livros", $sprite = "javascript_badge")
    Container(processor, "Processador de Reservas", "JavaScript", "Processa as reservas: confirmando ou rejeitando", $sprite = "javascript_badge")
    ContainerDb(mysql_processor, "Banco de dados", "MySQL", "Armazena os detalhes das reservas de ingressos e livros")
    Container(powerbi, "Métricas do Sistema", "Power BI", "Armazena métricas de desempenho do sistema")
    Container(datastudio, "Dashboard de Métricas", "Data Studio", "Exibe métricas do sistema")
    Container(frontend, "Painel de Controle", "React", "Monitora as reservas de ingressos, eventos e livros", $sprite = "react")
    
    Rel(visitor, backend, "Solicita reserva de ingresso ou livro em", "HTTP/JSON")
    Rel(librarian, frontend, "Gerencia reservas e eventos em", "HTTPS")
    Rel(admin, datastudio, "Consume métricas de desempenho em", "HTTPS")
    Rel(frontend, backend, "Recupera informações de reservas e eventos", "HTTPS/JSON")
    Rel(backend, mysql_processor, "Armazena informações de reservas", "MySQL Protocol")
    Rel(backend, processor, "Envia detalhes da reserva para", "Através do Kafka pelo tópico reservations", $tags = "async")
    Rel(processor, mysql_processor, "Armazena detalhes das reservas", "MySQL Protocol")
    Rel(processor, backend, "Envia resultado da reserva para", "Através do Kafka pelo tópico reservation_results", $tags = "async")
    Rel(powerbi, processor, "Consume métricas de desempenho em", "HTTP/TXT")
    Rel(datastudio, powerbi, "Consume métricas de desempenho em", "PromQL")
}

@enduml
