@startuml
' Define abstract classes
class Product {
  - id: int
  - tipo: string
}

class Ingresso extends Product {
  - data: date
  - hora: time
  - valor: float
}

class Biblioteca extends Product {
  - tituloLivro: string
  - autor: string
  - dataPublicacao: date
  - editora: string
}

' Define abstract creator classes
class Creator {
  - factoryMethod(): Product
}

class VendaIngressoCreator extends Creator {
  - factoryMethod(): Ingresso
}

class ReservaBibliotecaCreator extends Creator {
  - factoryMethod(): Biblioteca
}

@enduml

